== Numbers

Onyx follows https://en.wikipedia.org/wiki/Number[Wikipedia] in terms of numeric types hierarchy.

=== Real numbers

> In mathematics, a real number is a value of a continuous quantity that can represent a distance along a line (or alternatively, a quantity that can be represented as an infinite decimal expansion).
> -- Wikipedia contributors, https://en.wikipedia.org/wiki/Real_number

In Onyx, a _real number_ type stem:[RR] simply derives the `Real` trait which in turn is a distinct alias to the zero-dimension `Hypercomplex<0>` specialization.

Bultin real number types are are `Int`, `Float` and `Fixed`.

==== `Int`

* `Int*` -- a signed binary integer with variable bitsize;
* `UInt*` -- an unsigned binary integer with variable bitsize;

* `Bit`
* `Byte` -- alias to `UInt8`;

==== `Float`

* `Float*` -- an IEEE 754 binary floating point number with variable bitsize;

==== `Fixed`

`1q8.2 : Fixed8<2>`, `1uq8.2 : UFixed8<2>`, `0xabq8.2`

=== Hyper complex numbers

> In mathematics, hypercomplex number is a traditional term for an element of a finite-dimensional unital algebra over the field of real numbers.
> -- Wikipedia contributors, https://en.wikipedia.org/wiki/Hypercomplex_number

* `Hypercomplex<T, D>` -- a hypercomplex number;
* `Complex<T> : Hypercomplex<T, 1>` -- a complex number, e.g. `2 + 1j`;
* `Quaternion<T> : Hypercomplex<T, 4>` -- a quaternion;

== `Ratio`

`Ratio<T>` -- a number ratio, e.g. `1 / 2 : Ratio<Int32>`;

== `Range`

`Range<T>` -- a range, e.g. `1..10 : Range<Int32>`;
